spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/jetStreamNavigatorDB
    username: jet-stream-navigator
    password: admin12345
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true